//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dynamic
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public int PhotoId { get; set; }
        public int PropertiesId { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual Proprietate Properties { get; set; }
    }
}
